apiVersion: v1
clusters:
  - cluster:
      certificate-authority: {0}
      server: https://127.0.0.1:{1,number,#}
    name: jenvtest
contexts:
  - context:
      cluster: jenvtest
      namespace: default
      user: jenvtest
    name: jenvtest
current-context: jenvtest
kind: Config
preferences: '{'}
users:
  - name: jenvtest
    user:
      client-certificate: {2}
      client-key: {3}
