#
# Copyright (C) 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: 2
jobs:

  OPENSHIFT_3.9.0:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            kube_version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
            curl -LO https://storage.googleapis.com/kubernetes-release/release/${kube_version}/bin/linux/amd64/kubectl && \
                chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            echo "Installed kubectl CLI tool"
            echo "Installing nsenter"
            if ! which nsenter > /dev/null; then
              echo "Did not find nsenter. Installing it."
              NSENTER_BUILD_DIR=$(mktemp -d /tmp/nsenter-build-XXXXXX)
              pushd ${NSENTER_BUILD_DIR}
              curl https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-2.31.tar.gz | tar -zxf-
              cd util-linux-2.31
              ./configure --without-ncurses
              make nsenter
              sudo cp nsenter /usr/local/bin
              rm -rf "${NSENTER_BUILD_DIR}"
              popd
            fi
            if ! which systemd-run > /dev/null; then
              echo "Did not find systemd-run. Hacking it to work around Kubernetes calling it."
              echo '#!/bin/bash
              echo "all arguments: "$@
              while [[ $# -gt 0 ]]
              do
                key="$1"
                if [[ "${key}" != "--" ]]; then
                  shift
                  continue
                fi
                shift
                break
              done
              echo "remaining args: "$@
              exec $@' | sudo tee /usr/bin/systemd-run >/dev/null
              sudo chmod +x /usr/bin/systemd-run
            fi
            oc_tool_version="openshift-origin-client-tools-v3.9.0-191fece-linux-64bit"
            curl -LO https://github.com/openshift/origin/releases/download/v3.9.0/${oc_tool_version}.tar.gz && \
                tar -xvzf ${oc_tool_version}.tar.gz && chmod +x $PWD/${oc_tool_version}/oc && sudo mv $PWD/${oc_tool_version}/oc /usr/local/bin/ && \
                rm -rf ${oc_tool_version}.tar.gz
            echo "Installed OC CLI tool"
            tmp=`mktemp`
            echo 'DOCKER_OPTS="$DOCKER_OPTS --insecure-registry 172.30.0.0/16"' > ${tmp}
            sudo mv ${tmp} /etc/default/docker
            sudo mount --make-shared /
            sudo service docker restart
            echo "Configured Docker daemon with insecure-registry"
            oc cluster up 
            sleep 10
            oc login -u system:admin
            echo "Configured OpenShift cluster : v3.9.0"
      - run:
          command: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B install -P itests-openshift
          no_output_timeout: 3600

  OPENSHIFT_3.10.0:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            kube_version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
            curl -LO https://storage.googleapis.com/kubernetes-release/release/${kube_version}/bin/linux/amd64/kubectl && \
                chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            echo "Installed kubectl CLI tool"
            echo "Installing nsenter"
            if ! which nsenter > /dev/null; then
              echo "Did not find nsenter. Installing it."
              NSENTER_BUILD_DIR=$(mktemp -d /tmp/nsenter-build-XXXXXX)
              pushd ${NSENTER_BUILD_DIR}
              curl https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-2.31.tar.gz | tar -zxf-
              cd util-linux-2.31
              ./configure --without-ncurses
              make nsenter
              sudo cp nsenter /usr/local/bin
              rm -rf "${NSENTER_BUILD_DIR}"
              popd
            fi
            if ! which systemd-run > /dev/null; then
              echo "Did not find systemd-run. Hacking it to work around Kubernetes calling it."
              echo '#!/bin/bash
              echo "all arguments: "$@
              while [[ $# -gt 0 ]]
              do
                key="$1"
                if [[ "${key}" != "--" ]]; then
                  shift
                  continue
                fi
                shift
                break
              done
              echo "remaining args: "$@
              exec $@' | sudo tee /usr/bin/systemd-run >/dev/null
              sudo chmod +x /usr/bin/systemd-run
            fi
            oc_tool_version="openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit"
            curl -LO https://github.com/openshift/origin/releases/download/v3.10.0/${oc_tool_version}.tar.gz && \
                tar -xvzf ${oc_tool_version}.tar.gz && chmod +x $PWD/${oc_tool_version}/oc && sudo mv $PWD/${oc_tool_version}/oc /usr/local/bin/ && \
                rm -rf ${oc_tool_version}.tar.gz
            echo "Installed OC CLI tool"
            tmp=`mktemp`
            echo 'DOCKER_OPTS="$DOCKER_OPTS --insecure-registry 172.30.0.0/16"' > ${tmp}
            sudo mv ${tmp} /etc/default/docker
            sudo mount --make-shared /
            sudo service docker restart
            echo "Configured Docker daemon with insecure-registry"
            oc cluster up
            sleep 10
            oc login -u system:admin
            echo "Configured OpenShift cluster : v3.10.0"
      - run:
          command: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B install -P itests-openshift
          no_output_timeout: 3600
  OPENSHIFT_3.11.0:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            kube_version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
            curl -LO https://storage.googleapis.com/kubernetes-release/release/${kube_version}/bin/linux/amd64/kubectl && \
                chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            echo "Installed kubectl CLI tool"
            echo "Installing nsenter"
            if ! which nsenter > /dev/null; then
              echo "Did not find nsenter. Installing it."
              NSENTER_BUILD_DIR=$(mktemp -d /tmp/nsenter-build-XXXXXX)
              pushd ${NSENTER_BUILD_DIR}
              curl https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-2.31.tar.gz | tar -zxf-
              cd util-linux-2.31
              ./configure --without-ncurses
              make nsenter
              sudo cp nsenter /usr/local/bin
              rm -rf "${NSENTER_BUILD_DIR}"
              popd
            fi
            if ! which systemd-run > /dev/null; then
              echo "Did not find systemd-run. Hacking it to work around Kubernetes calling it."
              echo '#!/bin/bash
              echo "all arguments: "$@
              while [[ $# -gt 0 ]]
              do
                key="$1"
                if [[ "${key}" != "--" ]]; then
                  shift
                  continue
                fi
                shift
                break
              done
              echo "remaining args: "$@
              exec $@' | sudo tee /usr/bin/systemd-run >/dev/null
              sudo chmod +x /usr/bin/systemd-run
            fi
            oc_tool_version="openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit"
            curl -LO https://github.com/openshift/origin/releases/download/v3.11.0/${oc_tool_version}.tar.gz && \
                tar -xvzf ${oc_tool_version}.tar.gz && chmod +x $PWD/${oc_tool_version}/oc && sudo mv $PWD/${oc_tool_version}/oc /usr/local/bin/ && \
                rm -rf ${oc_tool_version}.tar.gz
            echo "Installed OC CLI tool"
            tmp=`mktemp`
            echo 'DOCKER_OPTS="$DOCKER_OPTS --insecure-registry 172.30.0.0/16"' > ${tmp}
            sudo mv ${tmp} /etc/default/docker
            sudo mount --make-shared /
            sudo service docker restart
            echo "Configured Docker daemon with insecure-registry"
            oc cluster up 
            sleep 10
            oc login -u system:admin
            echo "Configured OpenShift cluster : v3.11.0"
      - run:
          command: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B install -P itests-openshift
          no_output_timeout: 3600
  RELEASE:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            bash ./scripts/prepare-environment.sh
            bash ./scripts/release.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - OPENSHIFT_3.9.0
      - OPENSHIFT_3.10.0
      - OPENSHIFT_3.11.0
      - RELEASE:
          filters:
            branches:
              only: release-project
